<?php
header('Content-Type: application/octet-stream');
header('Content-Disposition: attachment; filename="mikrotik.rsc"');

// Log fonksiyonu
function writeLog($message) {
    $logFile = 'debug.log';
    $timestamp = date('Y-m-d H:i:s');
    file_put_contents($logFile, "[$timestamp] $message\n", FILE_APPEND);
}

try {
    // IP listesini oku
    $ips = file_exists('blacklist_ips.txt') ? file('blacklist_ips.txt', FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) : [];
    
    // Script başlığı
    echo "# Mikrotik Firewall Address List Script\n";
    echo "# Generated by intRbl System\n";
    echo "# Last Update: " . date('Y-m-d H:i:s') . "\n\n";
    
    // Mevcut listeyi temizle
    echo "/ip firewall address-list remove [find list=rtbh]\n";
    echo "/ip firewall address-list\n";
    
    // IP'leri ekle
    foreach ($ips as $ip) {
        $ip = trim($ip);
        if (filter_var($ip, FILTER_VALIDATE_IP)) {
            echo "add list=rtbh comment=\"intRbl System - Auto Generated\" address=$ip\n";
        }
    }
    
    writeLog("Mikrotik script başarıyla oluşturuldu - " . count($ips) . " IP adresi");
} catch (Exception $e) {
    writeLog("Mikrotik script oluşturma hatası: " . $e->getMessage());
    die("# Error generating script: " . $e->getMessage());
}
?>