# Mikrotik Firewall Rules for intRbl
# Generated by intRbl System
# https://github.com/huseyin-gok/intRbl

/ip firewall address-list remove [/ip firewall address-list find list=rtbh]

/ip firewall address-list
add list=rtbh comment="intRbl - Auto Generated" address=1.0.0.1
add list=rtbh comment="intRbl - Auto Generated" address=1.0.128.207
add list=rtbh comment="intRbl - Auto Generated" address=1.0.138.115
add list=rtbh comment="intRbl - Auto Generated" address=1.0.157.36