# Mikrotik Firewall Address List Script
# Generated by intRbl System
# Last Update: {datetime}

/ip firewall address-list remove [find list=rtbh]
/ip firewall address-list
add list=rtbh comment="intRbl System - Auto Generated" address=1.0.0.1
add list=rtbh comment="intRbl System - Auto Generated" address=1.0.128.207
add list=rtbh comment="intRbl System - Auto Generated" address=1.0.138.115
add list=rtbh comment="intRbl System - Auto Generated" address=1.0.157.36